version: '3.8'

services:
  portfolio:
    image: abhay41/my_portfolio:latest
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - portfolio-network

  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  node_modules: {}
